### ISSUE TITLE
Incompatibility with IntelliJ Idea 2021.1

### ISSUE THREAD

**Issue by Heliosmaster** [mustangJaro/antandre#2]
As per title, IntelliJ warns that the plugin isn't compatible.

**Comment by mustangJaro** [comment]
@Heliosmaster thanks! I'll fix this in the next few days

**Comment by mustangJaro** [comment]
@Heliosmaster I just uploaded the new version today to the marketplace so that should mean it's available in a couple days to support 2021.1. Please create another issue if you encounter further problems. Thanks!!
